In [1]:
import pandas as pd
import numpy as np

In [19]:
np.array([5,6,7,8])

array([5, 6, 7, 8])

In [20]:
np.array([5,6,7,8],dtype=np.float32)

array([5., 6., 7., 8.], dtype=float32)

In [21]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# array of zero's

In [5]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.zeros(6,dtype=np.int32)

array([0, 0, 0, 0, 0, 0])

# array of ones

In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.ones(2,dtype=np.float32)

array([1., 1.], dtype=float32)

# random number in ndarray

In [13]:
np.random.rand(3,2)

array([[0.10687903, 0.32821661],
       [0.95706927, 0.12644722],
       [0.0406182 , 0.33118108]])

In [14]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

# Imatrix in numpy

In [25]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [26]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [17]:
np.eye(6,k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
np.eye(3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

# evenly spaced


In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,10,3)

array([0, 3, 6, 9])

# dimensions of numpy

In [36]:
a = np.array([[5,10,15],[20,25,20]])
a.ndim
a


array([[ 5, 10, 15],
       [20, 25, 20]])

In [34]:
a.ndim

2

# shape of numpy

In [60]:

b= np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
b.shape[0]


2

In [56]:
b.shape[1]

3

# size of numpy

In [58]:
b.size

6

# reshaping of numpy

In [61]:
a = np.array([3,6,9,12])
np.reshape(a,(2,2))


array([[ 3,  6],
       [ 9, 12]])

# flattening of numpy

In [81]:
a = np.ones((2,2))
b = a.flatten()
c = a.ravel()
print(a)

[[1. 1.]
 [1. 1.]]


In [82]:
a = np.ones((2,2))
b = a.flatten()
c = a.ravel()
print(b)

[1. 1. 1. 1.]


In [83]:
a = np.ones((4,2))
b = a.flatten()
c = a.ravel()
print(c)

[1. 1. 1. 1. 1. 1. 1. 1.]


# transpose

In [84]:
a = np.array([[1,2,3],
[4,5,6]])
b = np.transpose(a)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
b

array([[1, 4],
       [2, 5],
       [3, 6]])

# slicing 1-d

In [88]:
a = np.array([1,2,3,4,5,6])
print(a[1:5:2])


[2 4]


In [89]:
a = np.array([1,2,3,4,5,6])
print(a[1:6:2])

[2 4 6]


# slicing 2-d

In [102]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0:1,:])



[[1 2 3]]


# slicing 3-d

In [103]:
a = np.array([[[1,2],[3,4],[5,6]],
[[7,8],[9,10],[11,12]],
[[13,14],[15,16],[17,18]]])

print(a)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


# Negative slicing of NumPy arrays

In [104]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print(a[:,-1])


[ 5 10]


In [105]:
print(a[:,-1:-3:-1])


[[ 5  4]
 [10  9]]


# creating a data frame

In [106]:

import pandas as pd
 

data = [['tom', 10], ['nick', 15], ['juli', 14]]
 

df = pd.DataFrame(data, columns=['Name', 'Age'])
 

print(df)

   Name  Age
0   tom   10
1  nick   15
2  juli   14


# concat()


In [108]:
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

# Setting conditions

In [115]:
data = {'Book_Name': ['Arihant', 'Oxford', 'Pearson', 'Cengage', 'Disha'],
        'Author': ['Madhumita Pattrea', 'Oscar Wilde', 'Jhon Pearson', 'G Tewani', 'Disha'],
         'Price': [350,880,490,1100,450]}
  
df = pd.DataFrame(data)
df

Book_Name             Author  Price
0   Arihant  Madhumita Pattrea    350
1    Oxford        Oscar Wilde    880
2   Pearson       Jhon Pearson    490
3   Cengage           G Tewani   1100
4     Disha              Disha    450

In [117]:
df[(df['Price'] ==490)]

Book_Name        Author  Price
2   Pearson  Jhon Pearson    490

# adding a new column

In [119]:
df.insert(2,"no.of items",[1,4,5,6,7],True)
df

Book_Name             Author  no.of items  no.of items  Price
0   Arihant  Madhumita Pattrea            1            1    350
1    Oxford        Oscar Wilde            4            4    880
2   Pearson       Jhon Pearson            5            5    490
3   Cengage           G Tewani            6            6   1100
4     Disha              Disha            7            7    450

# csv file

In [120]:
dff=pd.read_csv('data.csv')
dff

Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.5
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0
15        60     98       120     215.2
16        60    100       120     300.0

# xlsx file

In [122]:
df=pd.read_excel('Book.xlsx')
df

name  age  marks
0   smith   25     86
1  parker   23     97
2    john   21     69

# json file

In [123]:
df=pd.read_json('posts.json')
df

body   id  \
0   quia et suscipit\nsuscipit recusandae consequu...    1   
1   est rerum tempore vitae\nsequi sint nihil repr...    2   
2   et iusto sed quo iure\nvoluptatem occaecati om...    3   
3   ullam et saepe reiciendis voluptatem adipisci\...    4   
4   repudiandae veniam quaerat sunt sed\nalias aut...    5   
5   ut aspernatur corporis harum nihil quis provid...    6   
6   dolore placeat quibusdam ea quo vitae\nmagni q...    7   
7   dignissimos aperiam dolorem qui eum\nfacilis q...    8   
8   consectetur animi nesciunt iure dolore\nenim q...    9   
9   quo et expedita modi cum officia vel magni\ndo...   10   
10  delectus reiciendis molestiae occaecati non mi...   11   
11  itaque id aut magnam\npraesentium quia et ea o...   12   
12  aut dicta possimus sint mollitia voluptas comm...   13   
13  fuga et accusamus dolorum perferendis illo vol...   14   
14  reprehenderit quos placeat\nvelit minima offic...   15   
15  suscipit nam nisi quo aperiam aut\nasperiores ...   16   
16  eos voluptas et aut odit natus earum\naspernat...   17   
17  eveniet quo quis\nlaborum totam consequatur no...   18   
18  illum quis cupiditate provident sit magnam\nea...   19   
19  qui consequuntur ducimus possimus quisquam ame...   20   
20  repellat aliquid praesentium dolorem quo\nsed ...   21   
21  eos qui et ipsum ipsam suscipit aut\nsed omnis...   22   
22  veritatis unde neque eligendi\nquae quod archi...   23   
23  enim et ex nulla\nomnis voluptas quia qui\nvol...   24   
24  ullam consequatur ut\nomnis quis sit vel conse...   25   
25  similique esse doloribus nihil accusamus\nomni...   26   
26  eum sed dolores ipsam sint possimus debitis oc...   27   
27  non et quaerat ex quae ad maiores\nmaiores rec...   28   
28  odit magnam ut saepe sed non qui\ntempora atqu...   29   
29  alias dolor cumque\nimpedit blanditiis non eve...   30   
..                                                ...  ...   
70  occaecati a doloribus\niste saepe consectetur ...   71   
71  quam occaecati qui deleniti consectetur\nconse...   72   
72  voluptatem cumque tenetur consequatur expedita...   73   
73  odit qui et et necessitatibus sint veniam\nmol...   74   
74  commodi non non omnis et voluptas sit\nautem a...   75   
75  ut animi facere\ntotam iusto tempore\nmolestia...   76   
76  modi ut in nulla repudiandae dolorum nostrum e...   77   
77  nobis facilis odit tempore cupiditate quia\nas...   78   
78  libero accusantium et et facere incidunt sit d...   79   
79  ex quod dolorem ea eum iure qui provident amet...   80   
80  facere qui nesciunt est voluptatum voluptatem ...   81   
81  ut libero sit aut totam inventore sunt\nporro ...   82   
82  est molestiae facilis quis tempora numquam nih...   83   
83  sint molestiae magni a et quos\neaque et quasi...   84   
84  similique sed nisi voluptas iusto omnis\nmolli...   85   
85  quasi excepturi consequatur iste autem tempori...   86   
86  eos et molestiae\nnesciunt ut a\ndolores persp...   87   
87  consequatur omnis est praesentium\nducimus non...   88   
88  repellat aut aperiam totam temporibus autem et...   89   
89  minus omnis soluta quia\nqui sed adipisci volu...   90   
90  libero voluptate eveniet aperiam sed\nsunt pla...   91   
91  aut et excepturi dicta laudantium sint rerum n...   92   
92  dolorem quibusdam ducimus consequuntur dicta a...   93   
93  aspernatur expedita soluta quo ab ut similique...   94   
94  earum voluptatem facere provident blanditiis v...   95   
95  in non odio excepturi sint eum\nlabore volupta...   96   
96  eum non blanditiis soluta porro quibusdam volu...   97   
97  doloremque ex facilis sit sint culpa\nsoluta a...   98   
98  quo deleniti praesentium dicta non quod\naut e...   99   
99  cupiditate quo est a modi nesciunt soluta\nips...  100   

                                                title  userId  
0   sunt aut facere repellat provident occaecati e...       1  
1                                        qui est esse       1  
2   ea moles

# text file

In [125]:
df=pd.read_table('basic.txt')
df

The Zen of Python, by Tim Peters
0       Beautiful is better than ugly.
1    Explicit is better than implicit.
2       Simple is better than complex.
3  Complex is better than complicated.
4          Flat is better than nested.
5         Sparse is better than dense.
6                  Readability counts.